version: '3.7'
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d/

  sanbox-database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${SANBOX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SANBOX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SANBOX_POSTGRES_DB}
    ports:
      - '5433:5432'
